version: '3.1'

services:
    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql-enrichment:/var/lib/mysql
        ports: 
            - 3306:3306
        environment:
            MYSQL_DATABASE: nesped
            MYSQL_ROOT_PASSWORD: root

    elasticsearch:
        image: elasticsearch:7.6.2
        environment:
            - discovery.type=single-node
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - elasticsearch-enrichment:/usr/share/elasticsearch/data
volumes:
    elasticsearch-enrichment:
    mysql-enrichment:
