version: '3.1'

services:
    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./init.sql:/data/application/init.sql
            - mysql-enrichment:/var/lib/mysql
        ports: 
            - 3306:3306
        environment:
            MYSQL_DATABASE: moredata
            MYSQL_ROOT_PASSWORD: root
volumes:
    mysql-enrichment:
