name: moredata-docs
channels:
- conda-forge
dependencies:
- python=3.7
- requests=2.22.0
- SQLAlchemy=1.3.18
- PyMySQL=0.10.0
- osm2geojson=0.1.27
- Rtree=0.9.7
- pyproj=2.4.2.post1
- geopandas=0.7.0
- geopy=2.0.0
- pandas=1.0.1
- numpy=1.18.1
- elasticsearch=7.5.1
- shapely=1.7.0
- sphinx=2.4.0
- sphinx-rtd-theme==0.4.3
- jinja2==2.11.1
- sphinxcontrib-napoleon==0.7